import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Todo from './components/Todo'
import Authentication from './components/Auth'
import Welcome from './components/Home'
import DarkModeToggle from './components/DarkMode'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <header className='Nav' style={{ display: 'flex', justifyContent: 'space-between' }}>
            <Welcome />
            <Authentication />
          </header>

          <DarkModeToggle />
          <Todo />
        </div>
      </main>
    </>
  )
}
