#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]

switch (cmd) {
  case 'list':
    commands.list()
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}