#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]

switch (cmd) {
  case 'list':
    commands.list()
    break

  case 'done':
    commands.deleteTodo(userInputs[2])    
    break
    
  case 'add':
    console.log(userInputs)
    commands.addToDo(userInputs[3])
    break

  case 'update':
    commands.updateToDo(userInputs[3], userInputs[4])
    break

  default:
    console.log("I don't understand that command:" + cmd)
}
