#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv[2]
const cmd = userInputs

switch (cmd) {
  case 'list':
    commands.list()
    break

  default:
    console.log(`I don't understand that command: ${cmd}`)
}

console.log('hello');